"""empty message

Revision ID: 3be945cad341
Revises: d574859a7da8
Create Date: 2022-11-19 14:20:58.460463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3be945cad341'
down_revision = 'd574859a7da8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_session', schema=None) as batch_op:
        batch_op.drop_column('device')

    # ### end Alembic commands ###
