"""empty message

Revision ID: 639629124af5
Revises: 4fefbd413355
Create Date: 2022-10-21 21:06:51.376739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '639629124af5'
down_revision = '4fefbd413355'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_type', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('account_type')

    # ### end Alembic commands ###
