"""empty message

Revision ID: d574859a7da8
Revises: 0b308716b641
Create Date: 2022-11-19 14:01:11.881180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd574859a7da8'
down_revision = '0b308716b641'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('uuid')

    with op.batch_alter_table('user_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires', sa.DateTime(), nullable=True))
        batch_op.drop_column('token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token', sa.VARCHAR(length=128), nullable=True))
        batch_op.drop_column('expires')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.VARCHAR(length=16), nullable=True))

    # ### end Alembic commands ###
