"""empty message

Revision ID: 23a6004110c5
Revises: e5e181d59439
Create Date: 2022-11-23 22:18:15.373702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23a6004110c5'
down_revision = 'e5e181d59439'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_session', schema=None) as batch_op:
        batch_op.drop_column('platform')
        batch_op.drop_column('browser')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('browser', sa.VARCHAR(length=32), nullable=True))
        batch_op.add_column(sa.Column('platform', sa.VARCHAR(length=32), nullable=True))

    # ### end Alembic commands ###
