"""empty message

Revision ID: e5e181d59439
Revises: c38fe639ebb3
Create Date: 2022-11-23 17:17:54.359914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5e181d59439'
down_revision = 'c38fe639ebb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('browser', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_session', schema=None) as batch_op:
        batch_op.drop_column('browser')
        batch_op.drop_column('platform')

    # ### end Alembic commands ###
